---
abstract: 'create a fake infix operator'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Sub::Infix
name: Sub-Infix
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Sub-Infix
  homepage: https://metacpan.org/release/Sub-Infix
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-sub-infix
version: 0.002
